import Head from "next/head";
import IconDiagramSuccessor from "@/Icons/IconDiagramSuccessor";
import Button from "@/components/Button/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          flexDirection: "column",
          paddingTop: "10px",
          gap: "20px",
        }}
      >
        <h1>COLORS</h1>
        <div
          style={{
            display: "flex",
            gap: "20px",
          }}
        >
          <Button color="default" label="Default!" />
          <Button color="primary" label="Primary!" />
          <Button color="secondary" label="Secondary!" />
          <Button color="duo" label="Duo!" />
          <Button color="marketplace" label="Marketplace!" />
          <Button color="error" label="Error!" />
        </div>
        <h1>OUTLINED</h1>
        <div>
          <Button color="default" label="Outlined!" />
        </div>
        <div>
          <h1>WITH ICON</h1>
          <Button color="duo" label="With Icon">
            <IconDiagramSuccessor name="icon" />
          </Button>
        </div>
        <h1>DISABLED</h1>
        <div>
          <Button color="default" disabled label="Outlined!" />
        </div>

        <h1>SHAPE</h1>
        <div>
          <Button color="primary" shape="tile" label="PILL!" />
        </div>

        <h1>SIZES</h1>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "20px",
          }}
        >
          <Button color="primary" dimension="small" label="Small!" />
          <Button color="secondary" dimension="large" label="Large!" />
        </div>
      </main>
    </>
  );
}
